name = "roll-dorado-casino-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-dorado-casino.de"
HMAC_KEY = "75ddce0ab22c30d7e7525689cad43de036854c84ffa2adad7b3d15ac900e17c0"
COOKIE_NAME = "e94"
PLAY_PATH = "start"
BUTTON_ID = "p95c2a2e579af22a10076fa97865804ba"
GATE_SALT = "0296d6a6c4a6f1b8"
