name = "roll-dorado-casino-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-dorado-casino.de"
HMAC_KEY = "75ddce0ab22c30d7e7525689cad43de036854c84ffa2adad7b3d15ac900e17c0"
COOKIE_NAME = "0aq"
PLAY_PATH = "play"
BUTTON_ID = "p95c2a2e579af22a10076fa97865804ba"
GATE_SALT = "ae1263246da89e26"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "mhx6"
CTA_SELECTOR = ".play-button"
